[theme]
theme = "solarized-dark"

[icons]
icons = "awesome6"

[[block]]
block = "disk_space"
path = "/"
info_type = "used"
format = "$icon ROOT: $used/$total ($available free)"
alert = 80
warning = 60

[[block]]
block = "disk_space"
path = "/home/emmathorpe"
info_type = "used"
format = "$icon HOME: $used/$total ($available free)"
alert = 80
warning = 60

[[block]]
block = "battery"
format = "$icon $percentage $time"

[[block]]
block = "temperature"
interval = 10
format = "$icon $average"
chip = "coretemp-isa-*"
inputs = ["Package id 0"]

[[block]]
block = "net"
device = "wlan0"
format = "^icon_net_down $speed_down.eng(prefix:K) ^icon_net_up $speed_up.eng(prefix:K)"
interval = 5

[[block]]
block = "memory"
format = " $icon $mem_used_percents "

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "$icon $1m"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 5
[block.format]
full = " $icon $timestamp.datetime(f:'%a %d/%m %R') "

