# Linux specific configuration
if [ "$(uname -s)" != "Darwin" ]; then
    source /etc/os-release
    # Arch Linux specific configuration
    if [ "$ID" = "arch" ]; then
        # Add macOS aliases
        alias pbcopy="xclip -sel clip"
        alias pbpaste="xclip -out -sel clip"
    fi
    # Start sway
    if [ -z $DISPLAY  ] && [ "$(tty)" = "/dev/tty1"  ]; then
        export QT_QPA_PLATFORM="wayland;xcb"
        export QT_QPA_PLATFORMTHEME=qt5ct
        export CLUTTER_BACKEND=wayland
        export SDL_VIDEODRIVER=wayland
        export WINIT_UNIX_BACKEND=x11
        export MOZ_ENABLE_WAYLAND=1
        export _JAVA_AWT_WM_NONREPARENTING=1
        exec sway
    fi
    # Set up devKitPro
    export DEVKITPRO=/opt/devkitpro
    export DEVKITARM=/opt/devkitpro/devkitARM
    export DEVKITPPC=/opt/devkitpro/devkitPPC
fi
# macOS specific configuration
if [ "$(uname -s)" = "Darwin" ]; then
    # Add MacPorts to PATH 
    export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
    if [ "$(uname -m)" = "arm64" ]; then
        export PATH="/opt/homebrew/bin:$PATH"
    fi
fi
# zsh-history-substring-search configuration
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
bindkey '^[OA' history-substring-search-up
bindkey '^[OB' history-substring-search-down
HISTORY_SUBSTRING_SEARCH_ENSURE_UNIQUE=1
# Functions to enable .kube/config
mmrk8s() {
    export KUBECONFIG=$HOME/.kube/mmr-config
}
cbgk8s() {
    export KUBECONFIG=$HOME/.kube/cbg-config
}
# Misc aliases
alias cls=clear
alias enby=man
# Misc variables
export THEFUCK_PRIORITY="git_hook_bypass=1100"
export PATH=$HOME/.bin:$HOME/.local/bin:$PATH

if [ "$SSH_CLIENT" ] || [ "$SSH_TTY" ]; then
    export PS1=%M\ $PS1
fi

# Enable thefuck
eval $(thefuck --alias)
