export SYSTEM_PLATFORM=$(uname -s)
export SYSTEM_ARCH=$(uname -m)


if [ $SYSTEM_PLATFORM = "Darwin" ]; then
    if [ $SYSTEM_ARCH = "arm64" ]; then
        # Setup brew arm64
        export HOMEBREW_PREFIX="/opt/homebrew";
        export HOMEBREW_CELLAR="/opt/homebrew/Cellar";
        export HOMEBREW_REPOSITORY="/opt/homebrew";
        export MANPATH="/opt/homebrew/share/man${MANPATH+:$MANPATH}:";
        export INFOPATH="/opt/homebrew/share/info:${INFOPATH:-}";

        # Work variables and aliases
        export LW_PROFILE=dev7
        alias lw=lacework
    else
        # Setup brew x86
        export HOMEBREW_PREFIX="/usr/local";
        export HOMEBREW_CELLAR="/usr/local/Cellar";
        export HOMEBREW_REPOSITORY="/usr/local/Homebrew";
        export MANPATH="/usr/local/share/man${MANPATH+:$MANPATH}:";
        export INFOPATH="/usr/local/share/info:${INFOPATH:-}";
    fi
else # assume we're on Linux
fi

# Misc variables
export EDITOR=vim

# Misc aliases
alias cls=clear
